FROM grafana/grafana@sha256:f27625018abf2ff46b2d6ed6055e93565fa1ca7ca10a258763c0f1556fee75c7

USER root
RUN apk add curl jq

COPY ./provisioning /etc/grafana/provisioning
COPY ./*.sh ./

ENTRYPOINT ["./entry.sh"]
