FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3-build

RUN pip install smbus bme680 influxdb

WORKDIR /usr/src/app

COPY ./scripts ./scripts
RUN chmod +x scripts/*.py

CMD /usr/src/app/scripts/take_measurement.py
