FROM balenalib/%%BALENA_MACHINE_NAME%%-python:build

WORKDIR /tmp
RUN git clone https://github.com/RPi-Distro/RTIMULib/ RTIMU
WORKDIR /tmp/RTIMU/Linux/python
RUN python ./setup.py build
RUN python ./setup.py install

RUN pip install smbus bme680 influxdb sense-hat

WORKDIR /usr/src/app

COPY ./scripts ./scripts
RUN chmod +x scripts/*.py

CMD /usr/src/app/scripts/take_measurement.py
