FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine:3.11

RUN apk add influxdb

RUN sed -i 's|/var/lib/influxdb|/data/influxdb|g' /etc/influxdb.conf
RUN mkdir /etc/influxdb
RUN cp /etc/influxdb.conf /etc/influxdb/

CMD ["influxd"]
